root: true
env:
  node: true
  es2022: true
extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@next/next/recommended
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
  project:
    - ./tsconfig.json
    - ./packages/*/tsconfig.json
plugins:
  - '@typescript-eslint'
  - simple-import-sort
  - import
ignorePatterns:
  - node_modules/
  - dist/
settings:
  import/parsers:
    '@typescript-eslint/parser':
      - .ts
      - .tsx
  import/resolver:
    typescript:
      project:
        - ./tsconfig.json
        - ./packages/*/tsconfig.json
rules:
  simple-import-sort/imports:
    - error
    - groups:
        - - ^\u0000
        - - '^node:'
        - - ^@?\w
        - - ^spatial-id-
        - - ^#app/
        - - ^
        - - ^\.
  simple-import-sort/exports: error
  no-restricted-imports:
    - warn
    # - patterns:
    #     - group:
    #         - ../*
    #         - ./*
    #       message: Absolute imports by @/ are preferred.
  no-constant-condition:
    - error
    - checkLoops: false
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/triple-slash-reference': off
  '@next/next/no-img-element': off
globals:
  document: true
  window: true
